/**
 * Example API
 * This API allows writing down marks on a Tic Tac Toe board and requesting the state of the board or of individual squares. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Board {
    'test'?: string;
    'testInteger'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "test",
            "baseName": "test",
            "type": "string"
        },
        {
            "name": "testInteger",
            "baseName": "testInteger",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Board.attributeTypeMap;
    }
}

